name: Update README

on:
  push:
    branches: [ main ]

jobs:
  update-readme:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Update README
        uses: npalm/action-docs-action@b1dd20339140224c1ffef389467e4fece8dc416b # v3.1.2
        with:
          readme: ./README.md
          actionFile: ./action.yml
          tocLevel: 2
          lineBreaks: LF

      - name: commit and push
        uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6.0.1
        with:
          commit_message: "Auto-update README.md"
          branch: "update-readme"
          push_options: '--force'
          create_branch: true

      - name: Create pull request
        uses: devops-infra/action-pull-request@ff118b4a7c24bac5a3c95acef59e9edd1fc37890 # v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: update-readme
          target_branch: main
          label: automated
          title: Update README.md
          body: "Automatically updated contents of README.md based on an updated action.yml file"
