name: Update README
on:
  push:
    branches: [ main ]

jobs:
  update-readme:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # ratchet:actions/checkout@v3
        with:
          fetch-depth: 3
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update README
        uses: npalm/action-docs-action@b1dd20339140224c1ffef389467e4fece8dc416b
        with:
          readme: README.md
          sourceFile: action.yml
          tocLevel: 2
          lineBreaks: LF

      # Create pull request if applicable (for now works only on PR from same repository, not from forks)
      - name: Create Pull Request with applied fixes
        id: cpr
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # ratchet:peter-evans/create-pull-request@v4
        with:
          commit-message: "Auto-update README.md"
          title: "Update Readme.md"
          labels: bot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create PR output
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
